### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#10]
How we are going to handle pagination in the requests and responses for the APIs. This overlaps with the hypermedia discussion. Currently we are using a page, and per_page parameters for GET requests. Now is the time to change or evolve.

**Comment by NeilMcKechnie** [comment]
Works for me....the Response should also include a "Total Count" so that if you are displaying paging in a UI, you know how far to go; you also often want to display the total count to users. is anything more subtle needed?

**Comment by timgdavies** [comment]
In cases of data synchronisation I've seen APIs make good use of a ```next```, ```prev``` (and sometimes ```first``` and ```last```) relations as part of response meta-data, instead of numbered pagination.

This may be worth considering.

**Comment by kinlane** [comment]
Well I didn't get any bites on hypermedia, which normally is how you'd do all of this. My concern at this point is shifting the schema too heavily in minor releases. So adding JSON envelope, and adding pagination, link relations, etc. would break things -- ideally this is a v2 thing. 

Which is why I suggested media types w/ hypermedia.

My second option here is adding as custom headers. Github does this. So with each response you'd get custom headers you could get any next/prev, first/last, and counts without disrupting the response schema, but didn't see many bites on header usage which always worries me. 

I really want these things in here....so, I'm thinking header is only non-breaking route.

**Comment by kinlane** [comment]
Github Pagination - https://developer.github.com/v3/guides/traversing-with-pagination/

**Comment by spilio** [comment]
A classic reference for all bootstrapers afaiac is Apigee's REST style guide presentation.  

https://www.slideshare.net/apigee/rest-design-webinar/37

They pretty much favor the **limit**/**offset** pattern.

**Comment by kinlane** [comment]
Once again I am advocating for the most basic use case as the default -- allowing CSV outputs for all resources.

Embracing that HTTP is the envelope, and keeping responses flat, and free of meta data, etc. 

Pushing pagination meta data into the header with the following custom headers:

```
      - in: header
        name: x-page-number
        description: The page number for current page.
        schema:
          type: number             
      - in: header
        name: x-page-size
        description: The number of records being returned per page.
        schema:
          type: number   
      - in: header
        name: x-page-count
        description: The the total number of pages being returned.
        schema:
          type: number           
      - in: header
        name: x-record-count
        description: The total number of records available overall.
        schema:
          type: number 
```

This will allow for consumer to position themselves within pagination without adding complexity to the response body.
