### ISSUE TITLE
Error Codes

### ISSUE THREAD

**Issue by kinlane** [openreferral/api-specification#47]
This is a project to begin defining a set of objects to be returned as part of error codes, providing a structure, and common language set to describe common, as well as custom error responses.

**Comment by kinlane** [comment]
I have added the base problem schema to HSDA - -using RFC 7807:

```
    problem:
      description: The meta_table_description table contains metadata about individual
        tables.
      properties:
        type:
          type: string
          description: A URI reference [RFC3986] that identifies the problem type.  This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be "about:blank".
        title:
          type: string
          description: A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4)'
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        status:
          type: string
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
      required:
        - type
        - title
        - detail
        - status 
```
I will add a handful of types based upon the most common errors -- which should be able to be added to without iterating upon the version (unless fields are added).
